#!/usr/bin/env bash

#===========================================================
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

#===========================================================
shopt -s nullglob
shopt -s histappend
shopt -s checkwinsize
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

#== ENV ====================================================
export XDG_STATE_HOME=$HOME/.local/state
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config

#===========================================================
alias l='ls'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'

eval "$(starship init bash)"
