#!/usr/bin/env bash
cd "$(dirname "${0}")"

echo -ne "

████████╗██╗   ██╗███╗   ███╗██████╗ ██╗     ███████╗██╗    ██╗███████╗███████╗██████╗ 
╚══██╔══╝██║   ██║████╗ ████║██╔══██╗██║     ██╔════╝██║    ██║██╔════╝██╔════╝██╔══██╗
   ██║   ██║   ██║██╔████╔██║██████╔╝██║     █████╗  ██║ █╗ ██║█████╗  █████╗  ██║  ██║
   ██║   ██║   ██║██║╚██╔╝██║██╔══██╗██║     ██╔══╝  ██║███╗██║██╔══╝  ██╔══╝  ██║  ██║
   ██║   ╚██████╔╝██║ ╚═╝ ██║██████╔╝███████╗███████╗╚███╔███╔╝███████╗███████╗██████╔╝
   ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚═════╝ ╚══════╝╚══════╝ ╚══╝╚══╝ ╚══════╝╚══════╝╚═════╝ 
  
"

source ./extras/keygen

sudo zypper install -y gcc
sudo zypper install -y openssl libopenssl-devel 
source ./extras/rust
sudo ln -sf /usr/bin/python3 /usr/bin/python

sudo zypper install -y bat 
sudo zypper install -y exa
sudo zypper install -y fd
sudo zypper install -y fish && source ./extras/fisher
sudo zypper install -y fortune
sudo zypper install -y flatpak
sudo zypper install -y fzf
sudo zypper install -y git
sudo zypper install -y helix
sudo zypper install -y hledger
sudo zypper install -y neovim && git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
sudo zypper install -y ripgrep
sudo zypper install -y starship
sudo zypper install -y tealdeer

sudo zypper install -y gnome-shell-extension-pop-shell
source ./extras/gnome-config

sudo zypper install -y alacritty
sudo flatpak install -y "com.mattjakeman.ExtensionManager"
sudo flatpak install -y "com.github.tchx84.Flatseal"
sudo flatpak install -y "com.google.Chrome"
sudo flatpak install -y "com.spotify.Client"
sudo flatpak install -y "nz.mega.MEGAsync"

