#!/usr/bin/env bash
cd "$(dirname "${0}")"

menu(){
    echo -ne "
 \e[34m                                                       \e[0m
 \e[34m   ███████╗███████╗██████╗  ██████╗ ██████╗  █████╗    \e[0m
 \e[34m   ██╔════╝██╔════╝██╔══██╗██╔═══██╗██╔══██╗██╔══██╗   \e[0m
 \e[34m   █████╗  █████╗  ██║  ██║██║   ██║██████╔╝███████║   \e[0m
 \e[34m   ██╔══╝  ██╔══╝  ██║  ██║██║   ██║██╔══██╗██╔══██║   \e[0m
 \e[34m   ██║     ███████╗██████╔╝╚██████╔╝██║  ██║██║  ██║   \e[0m
 \e[34m   ╚═╝     ╚══════╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝   \e[0m
 \e[34m
   OsTree Install Options
   ════════════════════════════════════════
    o) Os-Tree Update
    p) Os-Tree Layers
    e) Flatpak - Use Flathub 
    f) Flatpak - Install
    r) Git Repos
    s) Ssh Keygen
    g) Gnome
    k) Kde
\e[37m
   Toolbox Install Options
   ════════════════════════════════════════
    d) Dnf setup
    a) dotfiles
    c) Command line tools
    v) Virtualization
    q) Rust
    x) exit
\e[0m
    Select Version: "

    read -r version
    case $version in
      a) dotfiles ;;
      c) clis ;;
      d) dnf_setup ;;
      e) use_flathub ;;
      f) flatpaks ;;
      g) gnome ;;
      h) gnome-ostree  ;;
      i) source fisher ;;
      k) kde ;;
      o) sudo rpm-ostree upgrade ;;
      p) rpm-ostree install alacritty virt-manager
         toolbox create 
         ;;
      
      q) rust ;;
      r) git-clones ;;
      s) keygen $HOME/.ssh/github.com 
         #keygen $HOME/.ssh/gitlab.com 
         #keygen $HOME/.ssh/gitlab.gnome.com 
         ;;
      v) virt ;;
      *) exit 1 ;;
    esac
}

dotfiles(){
  # dotfiles from chezmoi
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply "https://github.com/jeffwindsor/dotfiles-chezmoi"

  # move executable to PATH
  sudo mv ./bin/chezmoi /usr/local/bin/ 

  # re-build fortune dats 
  $HOME/.config/fortune/build.sh
}

git-clones(){
  mkdir -p $HOME/Source
  mkdir -p $HOME/Source/gitlab.com/
  mkdir -p $HOME/Source/github.com/

  git clone git@github.com:jeffwindsor/startpage.git $HOME/Source/github.com/jeffwindsor/startpage
}

clis(){
  sudo dnf install -y alacritty

  # clis
  sudo dnf -y install bat 
  sudo dnf -y install exa
  sudo dnf -y install entr
  sudo dnf -y install fd-find
  sudo dnf -y install fish
  sudo dnf -y install fortune-mod
  sudo dnf -y install fzf
  sudo dnf -y install gitui
  sudo dnf -y install hledger
  sudo dnf -y install megatools
  sudo dnf -y install ripgrep
  sudo dnf -y install tealdeer
  sudo dnf -y install jetbrains-mono-fonts

  #helix editor
  sudo dnf -y copr enable varlad/helix
  sudo dnf -y install helix
}

rust(){
  # neovim
  #sudo dnf -y install gcc "gcc-c++" glibc-all-langpacks
  #sudo dnf -y install neovim && git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

  # rust
  sudo dnf -y install openssl openssl-devel 
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  source "$HOME/.cargo/env"
  cargo install cargo-update
  cargo install topgrade              # upgrade all things
  cargo install --locked zellij       # tmux++
  cargo install kalker                # terminal based calculator
  cargo install bottom                # system monitor (like htop)  
  cargo install ddh                   # duplicate file finder
  sudo dnf -y install cmake && cargo install starship --version 1.10.3

  # lang servers
  sudo dnf -y install pylsp rust-analyzer 
}

dnf_setup(){
  # update dnf config
  echo "max_parallel_downloads=10" | sudo tee -a /etc/dnf/dnf.conf
  echo "defaultyes=True" | sudo tee -a /etc/dnf/dnf.conf
  echo "fastestmirror=True" | sudo tee -a /etc/dnf/dnf.conf
  # add rpm fusion repositories
  sudo dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
  sudo dnf -y install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  sudo dnf -y upgrade
}

kde(){
  sudo dnf install -y alacritty
  sudo dnf install -y bismuth
}

virt(){
  sudo dnf install @virtualization
  sudo systemctl start libvirtd
  sudo systemctl enable libvirtd
}

keygen(){
  if [[ ! -f $1 ]]; then
    ssh-keygen -t ed25519 -f $1 -C "jeff.windsor@gmail.com"
  fi
}

flatpaks(){
  flatpak install -y "com.github.tchx84.Flatseal"
  flatpak install -y "com.google.Chrome"
  flatpak install -y "com.mattjakeman.ExtensionManager"
  flatpak install -y "com.spotify.Client"
  flatpak install -y "com.discordapp.Discord"
  flatpak install -y "org.zealdocs.Zeal"
  flatpak install -y "net.sourceforge.Klavaro" 
  flatpak install -y "com.valvesoftware.Steam"
  flatpak install -y "com.discordapp.Discord"
  # flatpak install -y "io.github.endless_sky.endless_sky" 
}

use_flathub(){
  # replace fedora flatpak repo with flathub
  flatpak remote-modify --no-filter --enable flathub
  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  flatpak install --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
  flatpak remote-delete fedora
} 

#gnome_extensions(){
  # favorite terminal

  # make fish default shell
  #sudo lchsh $(which fish)
  
  # extensions
  # sudo dnf -y install gnome-shell-extension-appindicator
  # sudo dnf -y install gnome-shell-extension-blur-my-shell
  # sudo dnf -y install gnome-shell-extension-caffeine
  # sudo dnf -y install gnome-shell-extension-just-perfection
  # sudo dnf -y install gnome-shell-extension-launch-new-instance
  # sudo dnf -y install gnome-shell-extension-openweather
  #===========================================================================
  # ALSO INSTALL THROUGH EXTENSION MANAGER LATER:
  #  * Forge
  #  * Simply Workspaces
  #  * Wallpaper Switcher
  #  * AppIndicator
  #  * Blur My SHell
  #  * Caffeine
  #  * Just Perfection
  #  * Launch New Instance
  #  * Open Weather
  #===========================================================================
#}

gnome(){
  # clear unwanted settings
  dconf write "/org/gnome/desktop/wm/keybindings/begin-move" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/begin-resize" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/cycle-group" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/cycle-group-backward" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/cycle-windows" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/cycle-windows-backward" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-last" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-input-source" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-input-source-backward" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-last" "@as []"
  dconf write "/org/gnome/mutter/keybindings/toggle-tiled-left" "@as []"
  dconf write "/org/gnome/mutter/keybindings/toggle-tiled-right" "@as []"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip" "@as []"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/logout" "@as []"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/magnifier" "@as []"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/screencast" "@as []"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/screenreader" "@as []"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/screenshot-clip" "@as []"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/window-screenshot-clip" "@as []"
  dconf write "/org/gnome/shell/keybindings/focus-active-notification" "@as []"
  
  # interface preferences
  dconf write "/org/gnome/desktop/calendar/show-weekdate" "true"
  dconf write "/org/gnome/desktop/datetime/automatic-timezone" "true"
  dconf write "/org/gnome/desktop/interface/clock-format" "'12h'"
  dconf write "/org/gnome/desktop/interface/clock-show-weekday" "true"
  dconf write "/org/gnome/desktop/interface/color-scheme" "'prefer-dark'"
  dconf write "/org/gnome/desktop/interface/gtk-theme" "'Adwaita-dark'"
  dconf write "/org/gnome/desktop/interface/locate-pointer" "true"
  dconf write "/org/gnome/desktop/interface/text-scaling-factor" "1.25"
  dconf write "/org/gnome/desktop/peripherals/touchpad/click-method" "'fingers'"
  dconf write "/org/gnome/desktop/peripherals/touchpad/natural-scroll" "true"
  dconf write "/org/gnome/desktop/peripherals/touchpad/speed" "0.4"
  dconf write "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled" "true"
  dconf write "/org/gnome/desktop/wm/preferences/button-layout" "'close:appmenu'"
  dconf write "/org/gnome/desktop/wm/preferences/num-workspaces" "10"
  dconf write "/org/gnome/mutter/dynamic-workspaces" "false"
  dconf write "/org/gnome/mutter/workspaces-only-on-primary" "true"
  dconf write "/org/gtk/settings/file-chooser/clock-format" "'12h'"

  # extension preferences
  dconf write "/org/gnome/shell/extensions/just-perfection/activities-button" "false"
  dconf write "/org/gnome/shell/extensions/just-perfection/app-menu-label" "false"
  dconf write "/org/gnome/shell/extensions/just-perfection/startup-status" "0"
  dconf write "/org/gnome/shell/extensions/openweather/actual-city" "2"
  dconf write "/org/gnome/shell/extensions/openweather/city" "'30.2711286,-97.7436995>Austin, Travis County, Texas, United States>0 && 39.7392364,-104.984862>Denver, Colorado, United States>0 && 34.2783355,-119.293174>Ventura, Ventura County, CAL Fire Southern Region, California, United States>0'"
  dconf write "/org/gnome/shell/extensions/WallpaperSwitcher/frequency" "1200"
  dconf write "/org/gnome/shell/extensions/WallpaperSwitcher/wallpaper-path" "'/var/home/mid/portable/wallpapers/desktop'"

  # keyboard bindings
  dconf write "/org/gnome/desktop/wm/keybindings/close" "['<Super>q']"
  dconf write "/org/gnome/desktop/wm/keybindings/minimize" "['<Super>w']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-10" "['<Primary><Super>0']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-1" "['<Primary><Super>1']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-2" "['<Primary><Super>2']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-3" "['<Primary><Super>3']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-4" "['<Primary><Super>4']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-5" "['<Primary><Super>5']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-6" "['<Primary><Super>6']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-7" "['<Primary><Super>7']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-8" "['<Primary><Super>8']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-9" "['<Primary><Super>9']"
  dconf write "/org/gnome/desktop/wm/keybindings/panel-run-dialog" "['<Primary>space']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-10" "['<Super>0']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1" "['<Super>1']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2" "['<Super>2']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3" "['<Super>3']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4" "['<Super>4']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5" "['<Super>5']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6" "['<Super>6']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7" "['<Super>7']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8" "['<Super>8']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9" "['<Super>9']"
  dconf write "/org/gnome/desktop/wm/keybindings/toggle-fullscreen" "['<Primary><Super>m']"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot" "['<Primary><Super>BackSpace']"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/control-center" "['<Super>comma']"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/home" "['<Super>f']"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/next" "['AudioForward']"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/previous" "['AudioRewind']"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/window-screenshot" "['<Super>BackSpace']"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/www" "['<Super>b']"
  dconf write "/org/gnome/shell/keybindings/toggle-message-tray" "['<Super>n']"

  # # load gnome terminal profiles
  # dconf load /org/gnome/terminal/legacy/profiles:/ < ./configs/gnome-terminal-profiles.dconf

  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings" "[\
      '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', \
      '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', \
      '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', \
      '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', \
      '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', \
      '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/']"

  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding" "'<Primary><Super>S'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command" "'systemctl suspend'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name" "'Suspend'"

  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding" "'<Primary><Super>L'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command" "'gnome-session-quit --logout --no-prompt'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name" "'Logout'"

  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding" "'<Primary><Super>R'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command" "'systemctl reboot'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name" "'Reboot'"

  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/binding" "'<Primary><Super>P'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/command" "'systemctl poweroff'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/name" "'Power-Off'"

  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/binding" "'<Ctrl><Super>t'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/command" "'env WINIT_UNIX_BACKEND=x11 alacritty'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/name" "'OSTree'"

  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/binding" "'<Super>t'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/command" "'env WINIT_UNIX_BACKEND=x11 alacritty -e bash -c \"SHELL=/usr/bin/zsh toolbox enter\"'"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/name" "'Terminal'"
}

menu
