#!/usr/bin/env bash
cd "$(dirname "${0}")" || exit


clear
echo -ne "
 \e[38;5;39m
███████╗███████╗██████╗  ██████╗ ██████╗  █████╗
██╔════╝██╔════╝██╔══██╗██╔═══██╗██╔══██╗██╔══██╗
█████╗  █████╗  ██║  ██║██║   ██║██████╔╝███████║
██╔══╝  ██╔══╝  ██║  ██║██║   ██║██╔══██╗██╔══██║
██║     ███████╗██████╔╝╚██████╔╝██║  ██║██║  ██║
╚═╝     ╚══════╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
\e[0m"

# update dnf config
#echo "max_parallel_downloads=20" | sudo tee -a /etc/dnf/dnf.conf
#echo "defaultyes=True" | sudo tee -a /etc/dnf/dnf.conf
#echo "fastestmirror=False" | sudo tee -a /etc/dnf/dnf.conf
#echo "cacheonly=True" | sudo tee -a /etc/dnf/dnf.conf

# add rpm fusion repositories
#sudo dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm
#sudo dnf -y install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm

###############################################################################
# make current
###############################################################################
sudo dnf -y upgrade

###############################################################################
# dnf installs
###############################################################################
sudo dnf -y install alacritty
sudo dnf -y install zsh zsh-autosuggestions zsh-syntax-highlighting
sudo dnf -y install jetbrains-mono-fonts

sudo dnf -y install bat
sudo dnf -y install exa
sudo dnf -y install entr
sudo dnf -y install fd-find
sudo dnf -y install fortune-mod
sudo dnf -y install fzf
sudo dnf -y install ranger
sudo dnf -y install ripgrep
sudo dnf -y install sd
sudo dnf -y install shellcheck
sudo dnf -y install tealdeer
sudo dnf -y install vifm

# neovim
sudo dnf -y install gcc "gcc-c++" glibc-all-langpacks
sudo dnf -y install neovim && git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# starship prompt
sudo dnf -y copr enable atim/starship
sudo dnf -y install starship

###############################################################################
# flatpak installs
###############################################################################
sudo dnf remove Firefox

# flatpak install -y "io.github.endless_sky.endless_sky"
# flatpak install -y "net.sourceforge.Klavaro"                    # typing
# flatpak install -y "org.videolan.VLC"
flatpak install -y "com.discordapp.Discord"
flatpak install -y "com.github.rafostar.Clapper"
flatpak install -y "com.github.tchx84.Flatseal"                 # flatpak sec manager
flatpak install -y "com.gitlab.davem.ClamTk"                    # virus
flatpak install -y "com.gitlab.newsflash"
flatpak install -y "com.google.Chrome"
flatpak install -y "com.mattjakeman.ExtensionManager"           # improved extension manager
flatpak install -y "com.spotify.Client"
flatpak install -y "com.valvesoftware.Steam"
flatpak install -y "io.podman_desktop.PodmanDesktop"
flatpak install -y "md.obsidian.Obsidian"
flatpak install -y "org.chromium.Chromium"
flatpak install -y "org.gnome.Evolution"
flatpak install -y "org.gnome.Firmware"
flatpak install -y "org.gnome.Photos"
flatpak install -y "org.gnome.Podcasts"
flatpak install -y "org.gnome.seahorse.Application"
flatpak install -y "org.gnucash.GnuCash"
flatpak install -y "org.zealdocs.Zeal"                          # dev docs

###############################################################################
# gnome config
###############################################################################
  mod="<Super>"
  mod2="<Control>"

  # interface preferences
  dconf write "/org/gnome/desktop/calendar/show-weekdate" "true"
  dconf write "/org/gnome/desktop/datetime/automatic-timezone" "true"
  dconf write "/org/gnome/desktop/interface/clock-format" "'12h'"
  dconf write "/org/gnome/desktop/interface/clock-show-weekday" "true"
  dconf write "/org/gnome/desktop/interface/color-scheme" "'prefer-dark'"
  dconf write "/org/gnome/desktop/interface/gtk-theme" "'Adwaita-dark'"
  dconf write "/org/gnome/desktop/interface/locate-pointer" "true"
  dconf write "/org/gnome/desktop/interface/text-scaling-factor" "1.25"
  dconf write "/org/gnome/desktop/peripherals/touchpad/click-method" "'fingers'"
  dconf write "/org/gnome/desktop/peripherals/touchpad/natural-scroll" "true"
  dconf write "/org/gnome/desktop/peripherals/touchpad/speed" "0.4"
  dconf write "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled" "true"
  dconf write "/org/gnome/desktop/wm/preferences/button-layout" "'close:appmenu'"
  dconf write "/org/gnome/desktop/wm/preferences/num-workspaces" "10"
  dconf write "/org/gnome/mutter/dynamic-workspaces" "false"
  dconf write "/org/gnome/mutter/workspaces-only-on-primary" "true"
  dconf write "/org/gtk/settings/file-chooser/clock-format" "'12h'"

  # extension preferences
  dconf write "/org/gnome/shell/extensions/just-perfection/activities-button" "false"
  dconf write "/org/gnome/shell/extensions/just-perfection/app-menu-label" "false"
  dconf write "/org/gnome/shell/extensions/just-perfection/startup-status" "0"

  dconf write "/org/gnome/shell/extensions/openweather/actual-city" "2"
  dconf write "/org/gnome/shell/extensions/openweather/city" "'30.2711286,-97.7436995>Austin, Travis County, Texas, United States>0 && 39.7392364,-104.984862>Denver, Colorado, United States>0 && 34.2783355,-119.293174>Ventura, Ventura County, CAL Fire Southern Region, California, United States>0'"

  dconf write "/org/gnome/shell/extensions/WallpaperSwitcher/frequency" "1200"
  dconf write "/org/gnome/shell/extensions/WallpaperSwitcher/wallpaper-path" "'/var/home/mid/portable/wallpapers/desktop'"

  dconf write "/org/gnome/shell/extensions/forge/frequency/tiling-mode-enabled" "true"
  dconf write "/org/gnome/shell/extensions/forge/frequency/window-gap-size-increment" "1"

  # keyboard shortcuts
  # Launchers
  #   Settings
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/control-center" "['${mod}comma']"
  #   Files @ Home Folder
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/home" "['${mod}f']"
  #   Browser
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/www" "['${mod}b']"

  # Navigation
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-10" "['${mod}${mod2}0']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-1" "['${mod}${mod2}1']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-2" "['${mod}${mod2}2']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-3" "['${mod}${mod2}3']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-4" "['${mod}${mod2}4']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-5" "['${mod}${mod2}5']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-6" "['${mod}${mod2}6']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-7" "['${mod}${mod2}7']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-8" "['${mod}${mod2}8']"
  dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-9" "['${mod}${mod2}9']"
  dconf write "/org/gnome/shell/keybindings/switch-to-application-10" "@as []"
  dconf write "/org/gnome/shell/keybindings/switch-to-application-9" "@as []"
  dconf write "/org/gnome/shell/keybindings/switch-to-application-8" "@as []"
  dconf write "/org/gnome/shell/keybindings/switch-to-application-7" "@as []"
  dconf write "/org/gnome/shell/keybindings/switch-to-application-6" "@as []"
  dconf write "/org/gnome/shell/keybindings/switch-to-application-5" "@as []"
  dconf write "/org/gnome/shell/keybindings/switch-to-application-4" "@as []"
  dconf write "/org/gnome/shell/keybindings/switch-to-application-3" "@as []"
  dconf write "/org/gnome/shell/keybindings/switch-to-application-2" "@as []"
  dconf write "/org/gnome/shell/keybindings/switch-to-application-1" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-10" "['${mod}0']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1" "['${mod}1']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2" "['${mod}2']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3" "['${mod}3']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4" "['${mod}4']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5" "['${mod}5']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6" "['${mod}6']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7" "['${mod}7']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8" "['${mod}8']"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9" "['${mod}9']"

  # Screen shots
  dconf write "/org/gnome/shell/keybindings/show-screenshot-ui" "['<Control>grave']"

  # Sound and Media
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/next" "['AudioForward']"
  dconf write "/org/gnome/settings-daemon/plugins/media-keys/previous" "['AudioRewind']"

  # System
  dconf write "/org/gnome/shell/keybindings/focus-active-notification" "@as []"
  dconf write "/org/gnome/shell/keybindings/toggle-message-tray" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/panel-run-dialog" "['${mod2}space']"

  # Typing
  dconf write "/org/gnome/desktop/wm/keybindings/switch-input-source" "@as []"
  dconf write "/org/gnome/desktop/wm/keybindings/switch-input-source-backward" "@as []"

  # Windows
  dconf write "/org/gnome/desktop/wm/keybindings/close" "['${mod}q']"
  dconf write "/org/gnome/desktop/wm/keybindings/minimize" "['${mod}w']"
  dconf write "/org/gnome/desktop/wm/keybindings/toggle-fullscreen" "['${mod}${mod2}m']"
  dconf write "/org/gnome/mutter/keybindings/toggle-tiled-right" "@as []"
  dconf write "/org/gnome/mutter/keybindings/toggle-tiled-left" "@as []"

  # Custom
  custom_keys="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
  custom="${custom_keys}/custom"

  dconf write "$custom_keys" "[\
    '${custom}0/','${custom}1/','${custom}2/','${custom}3/',\
    '${custom}4/','${custom}5/','${custom}6/','${custom}7/',\
    '${custom}8/']"

  dconf write "${custom}0/binding" "'${mod}${mod2}l'"
  dconf write "${custom}0/command" "'gnome-session-quit'"
  dconf write "${custom}0/name" "'Logout'"

  dconf write "${custom}1/binding" "'${mod}${mod2}p'"
  dconf write "${custom}1/command" "'systemctl poweroff'"
  dconf write "${custom}1/name" "'Power-Off'"

  dconf write "${custom}2/binding" "'${mod}${mod2}r'"
  dconf write "${custom}2/command" "'systemctl reboot'"
  dconf write "${custom}2/name" "'Reboot'"

  dconf write "${custom}3/binding" "'${mod}${mod2}s'"
  dconf write "${custom}3/command" "'systemctl suspend'"
  dconf write "${custom}3/name" "'Suspend'"

  dconf write "${custom}4/binding" "'${mod}${mod2}t'"
  dconf write "${custom}4/command" "'env WINIT_UNIX_BACKEND=x11 alacritty --config-file \"$HOME\"/.config/alacritty/alacritty-ostree.yml -e bash -c \"SHELL=/usr/bin/zsh toolbox enter\"'"
  dconf write "${custom}4/name" "'Terminal2'"


  dconf write "${custom}5/binding" "'${mod}e'"
  dconf write "${custom}5/command" "'flatpak run com.mattjakeman.extensionmanager'"
  dconf write "${custom}5/name" "'Extensions'"

  dconf write "${custom}6/binding" "'${mod}g'"
  dconf write "${custom}6/command" "'gnucash'"
  dconf write "${custom}6/name" "'GNU Cash'"

  dconf write "${custom}7/binding" "'${mod}s'"
  dconf write "${custom}7/command" "'flatpak run com.spotify.client'"
  dconf write "${custom}7/name" "'Spotify'"

  dconf write "${custom}8/binding" "'${mod}t'"
  dconf write "${custom}8/command" "'env WINIT_UNIX_BACKEND=x11 alacritty'"
  dconf write "${custom}8/name" "'Terminal'"

###############################################################################
# gnome extesions
###############################################################################
install_gnome_extension(){
  # 1. GNOME shell version
  shell_version=$(gnome-shell --version | cut -d' ' -f3)

  # 2. Fetch extension info (for the given shell version) example input: 307
  info_json=$(curl -sS "https://extensions.gnome.org/extension-info/?pk=$1&shell_version=$shell_version")

  # 3. Extract download url from the json with jq
  download_url=$(echo $info_json | jq ".download_url" --raw-output)

  # 4. Install the extension
  echo "==> installing gnome $shell_version extension $1 from $download_url"
  gnome-extensions install "https://extensions.gnome.org$download_url"
}

# 615  | AppIndicator, https://github.com/ubuntu/gnome-shell-extension-appindicator, _
install_gnome_extension 615
# 3193 | Blur My Shell, https://github.com/aunetx/gnome-shell-extension-blur-my-shell, src
install_gnome_extension 3193
# 517  | Caffeine, https://github.com/eonpatapon/gnome-shell-extension-caffeine, caffeine@patapon.info
install_gnome_extension 517
# 2932 | Executor, https://github.com/raujonas/executor, executor@raujonas.github.io
install_gnome_extension 2932
# 4481 | Forge, https://github.com/jmmaranan/forge, _
install_gnome_extension 4481
# 3843 | Just Perfection, https://gitlab.gnome.org/jrahmatzadeh/just-perfection, src
install_gnome_extension 3843
# 5090 | Space Bar, https://github.com/christopher-l/space-bar, _
install_gnome_extension 5090
# 4812 | Wallpaper Switcher, https://github.com/rishuinfinity/WallpaperSwitcher, src
install_gnome_extension 4812
# 5470 | Weather O'Clock, https://github.com/CleoMenezesJr/weather-oclock, weatheroclock@CleoMenezesJr.github.io
install_gnome_extension 5470

###############################################################################
# dot files
###############################################################################
sh -c "$(curl -fsLS get.chezmoi.io)"
# move executable to PATH
sudo mv ./bin/chezmoi /usr/local/bin/

###############################################################################
# ssh key
###############################################################################
ssh-keygen -t ed25519 -C "jeff.windsor@gmail.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519

###############################################################################
#  post steps
###############################################################################
echo "========================================================================="
echo "Add ssh public key to Github"
cat $HOME/.ssh/*.pub
echo "Hit Any key when completed"
read -r

echo "\n==> Pulling and applying dotfiles"
chezmoi init --apply "https://github.com/jeffwindsor/dotfiles-chezmoi"

echo "\n==> Cloning Personal Github Repos"
git clone git@github.com:jeffwindsor/financials.git "$HOME"/Source/github.com/jeffwindsor/financials
git clone git@github.com:jeffwindsor/startpage.git "$HOME"/Source/github.com/jeffwindsor/startpage

echo "\nManual Install"
echo "==> MEGA: https://mega.io/desktop#downloadapps"

