#!/usr/bin/env bash

alias h='hx'
alias exo='hx ~/portable/exocortex'

alias configs='hx $XDG_CONFIG_HOME'
alias dots='hx $DOTFILES'
alias ins='hx $INSTALLS'

# direct to helix (old way)
# alias configs='hx $XDG_CONFIG_HOME'
# alias dots='hx $DOTFILES'
# alias ins='hx $INSTALLS'
