#!/usr/bin/env bash
cd "$(dirname "$0")" || exit
shopt -s extglob

echo "======================================================================="
toolbox list

files=(!(*.Containerfile))
for filename in "${files[@]}"
do
  tag="docker.io/jeffwindsor/${filename}:latest"

  echo "======================================================================="
  echo "removing any toolbox tagged as $filename"
  toolbox rm "$filename" --force

  echo "removing any image name $tag"
  toolbox rmi "$tag"

  echo "building podman image $tag from $filename"
  podman build --file="$filename" --tag="$tag"

  echo "creating toolbox $filename from image $tag"
  toolbox create "$filename" --image="$tag"

  echo
done

echo "======================================================================="
toolbox list
