theme = "gruvbox_dark_hard"

[editor]
auto-save = true
line-number = "absolute"
mouse = true
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = true
git-global = true

[editor.indent-guides]
render = true
character = "⸽"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
o = ["open_below", "normal_mode"]
O = ["open_above", "normal_mode"]
C-u = ["kill_to_line_start"]                              # like insert mode
C-k = ["kill_to_line_end"]                                # like insert mode
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

