theme = "kanagawa2"

[editor]
auto-save = true
line-number = "absolute"
mouse = true
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = true
git-global = true

[editor.indent-guides]
render = true
character = "|"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
# center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = " : "
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

# key remaps ##################################################################

[keys.normal]
C-u = ["kill_to_line_start"]
C-k = ["kill_to_line_end"] 
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
q = ":quit"

[keys.normal.space.b]        #buffers
b = "buffer_picker"
a = ":buffer-close-all"
c = ":buffer-close"
h = ":buffer-previous"
l = ":buffer-next"
n = ":new"

[keys.normal.space.c]        #config
c = ":config-open"
r = [":write", ":config-reload"]

[keys.normal.space.t]        #themes  
k = ":theme kanagawa2" 
n = ":theme nord" 
t = ":theme tokyonight_storm"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

