#!/usr/bin/env bash

echo "installing and configuring dotfiles"
sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply "https://github.com/jeffwindsor/dotfiles-chezmoi"

# move executable to PATH
sudo mv $HOME/bin/chezmoi /usr/local/bin/ 

echo "re-build fortune dats" 
$HOME/.config/fortune/build.sh
