#!/usr/bin/env bash

install_flatpaks(){

  flatpak install -y "com.github.tchx84.Flatseal"
  flatpak install -y "com.google.Chrome"
  flatpak install -y "com.mattjakeman.ExtensionManager"
  flatpak install -y "com.spotify.Client"
  flatpak install -y "com.discordapp.Discord"

  # flatpak install -y "nz.mega.MEGAsync"
  # flatpak install -y "net.sourceforge.Klavaro" 
  # flatpak install -y "com.visualstudio.code"
  # flatpak install -y "com.valvesoftware.Steam"
  # flatpak install -y "com.discordapp.Discord"
  # flatpak install -y "io.github.endless_sky.endless_sky" 
}

replace_fedora(){
  flatpak remote-modify --no-filter --enable flathub
  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  flatpak install --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
  flatpak remote-delete fedora
  #flatpak install --reinstall flathub name.of.application
} 

menu(){
  clear
  echo -ne "
  i) install flatpaks
  r) replace fedora with flathub 
  
  Select Step:  "
  read -r step
  case $step in
    i) install_flatpaks;;
    r) replace_fedora;; 
    *)
      echo "Not a valid option"
      exit 1
      ;;
  esac
}

menu
