#!/usr/bin/env fish

curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

fisher install PatrickF1/fzf.fish
fisher install gazorby/fish-exa
fisher install jorgebucaran/nvm.fish
fisher install reitzig/sdkman-for-fish@v1.4.0