#!/usr/bin/env bash

keygen(){
  if [[ ! -f $1 ]]; then
    ssh-keygen -t ed25519 -f $1 -C "jeff.windsor@gmail.com"
    ssh-agent -s
    ssh-add -k $1
    echo "== added ssh key: $1"
    cat $1.pub
  fi
}

keygen $HOME/.ssh/github.com 
#keygen $HOME/.ssh/gitlab.com 
#keygen $HOME/.ssh/gitlab.gnome.com 
