#!/usr/bin/env bash

echo "
===========================================================================
 INSTALL FOLLWING GNOME EXTENSIONS PRIOR TO CONTINUING
===========================================================================
  * AppIndicator
  * Blur My Shell
  * Caffiene
  * Containers (MAYBE)
  * Forge
  * Just Perfection
  * Open Weather
  * Simply Workspaces
  * Wallpaper Switcher
===========================================================================
Enter any key to continue:"
read  -n 1
echo ""

# clear unwanted settings
dconf write "/org/gnome/desktop/wm/keybindings/begin-move" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/begin-resize" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-group" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-group-backward" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-windows" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-windows-backward" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-last" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/switch-input-source" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/switch-input-source-backward" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-last" "@as []"
dconf write "/org/gnome/mutter/keybindings/toggle-tiled-left" "@as []"
dconf write "/org/gnome/mutter/keybindings/toggle-tiled-right" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/logout" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/magnifier" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/screencast" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/screenreader" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/screenshot-clip" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/window-screenshot-clip" "@as []"
dconf write "/org/gnome/shell/keybindings/focus-active-notification" "@as []"
  
# interface preferences
dconf write "/org/gnome/desktop/calendar/show-weekdate" "true"
dconf write "/org/gnome/desktop/datetime/automatic-timezone" "true"
dconf write "/org/gnome/desktop/interface/clock-format" "'12h'"
dconf write "/org/gnome/desktop/interface/clock-show-weekday" "true"
dconf write "/org/gnome/desktop/interface/color-scheme" "'prefer-dark'"
dconf write "/org/gnome/desktop/interface/gtk-theme" "'Adwaita-dark'"
dconf write "/org/gnome/desktop/interface/locate-pointer" "true"
dconf write "/org/gnome/desktop/interface/text-scaling-factor" "1.25"
dconf write "/org/gnome/desktop/peripherals/touchpad/click-method" "'fingers'"
dconf write "/org/gnome/desktop/peripherals/touchpad/natural-scroll" "true"
dconf write "/org/gnome/desktop/peripherals/touchpad/speed" "0.4"
dconf write "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled" "true"
dconf write "/org/gnome/desktop/wm/preferences/button-layout" "'close:appmenu'"
dconf write "/org/gnome/desktop/wm/preferences/num-workspaces" "10"
dconf write "/org/gnome/mutter/dynamic-workspaces" "false"
dconf write "/org/gnome/mutter/workspaces-only-on-primary" "true"
dconf write "/org/gtk/settings/file-chooser/clock-format" "'12h'"

# extension preferences
dconf write "/org/gnome/shell/extensions/just-perfection/activities-button" "false"
dconf write "/org/gnome/shell/extensions/just-perfection/app-menu-label" "false'"
dconf write "/org/gnome/shell/extensions/just-perfection/startup-status" "0"
dconf write "/org/gnome/shell/extensions/openweather/actual-city" "2"
dconf write "/org/gnome/shell/extensions/openweather/city" "'30.2711286,-97.7436995>Austin, Travis County, Texas, United States>0 && 39.7392364,-104.984862>Denver, Colorado, United States>0 && 34.2783355,-119.293174>Ventura, Ventura County, CAL Fire Southern Region, California, United States>0'"
dconf write "/org/gnome/shell/extensions/WallpaperSwitcher/frequency" "1200"
dconf write "/org/gnome/shell/extensions/WallpaperSwitcher/wallpaper-path" "'/var/home/mid/portable/wallpapers/desktop'"

# keyboard bindings
dconf write "/org/gnome/desktop/wm/keybindings/close" "['<Super>q']"
dconf write "/org/gnome/desktop/wm/keybindings/minimize" "['<Super>w']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-10" "['<Primary><Super>0']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-1" "['<Primary><Super>1']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-2" "['<Primary><Super>2']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-3" "['<Primary><Super>3']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-4" "['<Primary><Super>4']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-5" "['<Primary><Super>5']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-6" "['<Primary><Super>6']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-7" "['<Primary><Super>7']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-8" "['<Primary><Super>8']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-9" "['<Primary><Super>9']"
dconf write "/org/gnome/desktop/wm/keybindings/panel-run-dialog" "['<Primary>space']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-10" "['<Super>0']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1" "['<Super>1']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2" "['<Super>2']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3" "['<Super>3']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4" "['<Super>4']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5" "['<Super>5']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6" "['<Super>6']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7" "['<Super>7']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8" "['<Super>8']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9" "['<Super>9']"
dconf write "/org/gnome/desktop/wm/keybindings/toggle-fullscreen" "['<Primary><Super>m']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot" "['<Primary><Super>BackSpace']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/control-center" "['<Super>comma']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/home" "['<Super>f']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/next" "['AudioForward']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/previous" "['AudioRewind']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/window-screenshot" "['<Super>BackSpace']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/www" "['<Super>b']"
dconf write "/org/gnome/shell/keybindings/toggle-message-tray" "['<Super>n']"

# # load gnome terminal profiles
# dconf load /org/gnome/terminal/legacy/profiles:/ < ./configs/gnome-terminal-profiles.dconf
