#!/usr/bin/env bash
cd "$(dirname "$0")"

# build toolbox images and layers
#   TODO: use the --env=name=value for fedora verion in the FROM, ie 38 instead of latest if needed
filename="fedora-toolbox"

tag="docker.io/jeffwindsor/${filename}"
podman build --file="$filename" --tag="$tag"
toolbox create "$filename" --image="$tag"
